---
# tasks file for saad_inicial

- name: Atualizacao de Sistemas Operacionais Debian
  apt:
    name: "*"
    state: latest
    update_cache: yes
    autoremove: yes
  when: ansible_distribution == "Debian"


- name: Atualizacao de Sistemas operacionais CentOS
  dnf:
    name: "*"
    state: latest
    update_only: yes
  when: ansible_distribution == "CentOS"


#- name: Instalacao de pacotes basicos
#  package:
 #   name:
 #     - vim
 #     - bacula-client
 #     - net-tools
 #   state: latest

- name: Intalacao de pacotes basico (Debian)
  apt:
    name: "{{ common_packges_debian }}"
    state: latest
  when: ansible_distribution == "Debian"

- name: Instalacao de pacotes basicps CentOS
  yum:
    name: "{{ common_packges_centos }}"
    state: latest
  when: ansible_distribution == "CentOS"

- name: Desabilitando o SELINUX (Temporariamente)
  selinux: state=disabled
  when: ansible_distribution == "CentOS"

- name: Desabilitando o SELINUX (Permanentemente)
  replace:
    dest=/etc/selinux/config
    regexp='SELINUX=enforcing'
    replace='SELINUX=disabled'
  when: ansible_distribution == "CentOS"

- name: mudando /etc/profile
  lineinfile: dest=/etc/profile line={{ item }}
  loop:
    - '#--- Default export & Alias ---#'
    - 'export HISTSIZE="5000"'
    - 'export TERM=linux'
    - 'alias ls="ls -lh --color"'
    - 'alias grep="grep --color"'
    - 'alias vi="vim"'

- name: copiando .vimrc para usuario saad
  copy:
    src: .vimrc 
    dest: /home/saad/
    owner: saad
    group: saad
    mode: 0644

- name: copiando .vimrc para a pasta skel
  copy:
    src: .vimrc
    dest: /etc/skel/
    owner: root
    group: root
    mode: 0644

- name: Configurando o localtime
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes

- name: Configurando o Chrony (CentOS)
  lineinfile:
    dest: /etc/chrony.conf
    line: "Server 10.0.2.5"
  when: ansible_distribution == "CentOS"

- name: Configurando o Chrony (Debian)
  lineinfile:
    dest: /etc/chrony/chrony.conf
    line: "Server 10.0.2.5"
  when: ansible_distribution == "Debian"
  notify: Restart Chrony

- name: criando usuario ansible
  user:
    name: ansible
    groups: root
    system: yes
    generate_ssh_key: yes

- name: Criando o grupo clti 
  group: 
    name: clti
    state: present

- name: criando usuarios usando variaveis
  user:
    name: "{{ item.username }}"
    groups: clti
    generate_ssh_key: yes
  loop: "{{ users }}"
 #   - { username: 'dany'}
 #   - { username: 'figueiredo'}
 #   - { username: 'Lopes'}
    
- name: Copiando o SSH Key
  authorized_key:
    user: dany
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDcuMdw7a4zJY/f2mUt1MSvVFTtCDj60Zhp3zwFj4QScuzNAE5FC1Bf6tUhxTBgYQ+Lbl4l3A8SYvIXPuV8UpdJ5qf45W74a3CDQujxhu5nMUQwP5ev1QsJuTz61sUPaBsvcnim1CfWpRjN+7RGXSFPJD7LKmdkBflC5xnOE2WNFXBxA1d72MxKLGHCQ2LvGOIChva1WEp2wBGAjhaesdr+T2Nw5h7/Ja1YnfuyOWBEbC0Ax81IYFym0dsx9CUST8fWLqGr+9b7AOVeDV1TrgTPQjMHlQ6tgoOcNY864dv3zKVITLSlN73E7AUZ84vnhmUPUXJPJuchzSU+w5LCbviNtOysFh3uQ0QWMjOoeKU99PbwSzR+7vPHmi8gXmNV3XUEOa6G0wT+ueZ0R0YERfmEey7O9F9rwtciyTVlSBMhCcapU8rulrjcCbIJ4oriXU8waJd6nq4FRur0OiDaRn3bIKuqAUFAmUHaZ8QMWmwtWQ85BFDRBogcazOKwK4J0ns= dany@ansible"

- name: add user on Sudoers
  lineinfile:
    dest: /etc/sudoers
    line: '%clti  ALL=(ALL:ALL) NOPASSWD: ALL'

...
