---
# tasks file for samba4



### Parando o firewall desabilidanando da inicializacao e desabilitando o SELINUX

  - name: Parando o firewall 
    systemd: name=firewalld state=stopped     
  
  - name: Desabilitar o servico Firewalld da inicializacao 
    systemd: name=firewalld enabled=no
  
  - name: Desabilitando o SELINUX (temp)
    selinux: state=disabled

  - name: Desabilitando o SELINUX (permanente)
    replace: 
      path=/etc/selinux/config
      regexp='SELINUX=enforcing'
      replace='SELINUX=disabled'


## Instalando os pacotes basicos para instalacao do samba4
  - name: Instalacao de repositorio epel
    yum: name=epel-release state=latest

  - name: Habilitando Powertol repositorio
    replace:
      path=/etc/yum.repos.d/CentOS-Stream-PowerTools.repo
      regexp='enabled=0'
      replace='enabled=1'

  - name: Atualizando lista de repositorios
    yum: name=* state=latest

  - name: Instalacao de pacotes basicos
    yum: name={{ common_packges }} state=latest


## editar o arquivo /etc/hosts e nome da maquina

  - name: editar arquivo /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "10.0.2.4 clti9dnfs1.clti9d.ad clti9dnfs1"
  
  - name: Mudando o nome do servidor
    ansible.builtin.hostname:
      name: clti9dnfs1



## editar o arquivo /etc/sysctl.conf

  - name: Editando arquivo /etc/sysctl.conf
    lineinfile:
      path: /etc/sysctl.conf
      line: "vm.swappiness = 0"

##Editando o /etc/resolv.conf


  - name: Editando o /etc/resolv.conf
    lineinfile:
      path: /etc/resolv.conf
      line: "{{ item.line }}"
    loop:
      - { line: "nameserver {{ ansible_default_ipv4.address }} " }
      - { line: "nameserver 10.0.2.5" }
      - { line: "search {{ nome_dominio }}" }
      - { line: "domain {{ nome_dominio }}" }

## Movendo o instalador do samba para pasta /opt e descompactando o arquivo

  - name: Copiando o instalador do samba para pasta /opt
    copy: src=samba-latest.tar.gz dest=/opt

  - name: Extraindo o conteudo do instalador samba.tar.gz
    unarchive:  
      src: /opt/samba-latest.tar.gz
      dest: /opt/
      remote_src: yes


## executando o .configure && make && make install


#  - name: executando o .configure && make && make install
#    shell: ./configure.developer && make && make install
#    args: 
#      chdir: /opt/samba-4.15.2/

## exportar o samba/sbin samba/bin para o PATH

  - name: Exportando o sama/bin e samba/sbin para o PATH
    lineinfile:
      path: /home/saad/.bash_profile
      line: "export PATH=$PATH:/usr/local/samba/sbin:/usr/local/samba/bin"


## Editar o arquivo /etc/kr5.conf

  - name: zerando o arquivo /etc/krb5.conf
    shell: echo '[libdefaults]' > /etc/krb5.conf

  - name: Passando as variaveis para o /etc/krb5.conf
    lineinfile:
      path: /etc/krb5.conf
      line: "{{ item.line }}"
    loop:
      - { line: "default_realm {{ realm_nome }} " }
      - { line: "dns_lookup_realm = false" }
      - { line: "dns_lookup_kdc = true"}


## provisionando o samba

  - name: Provisionando o samba4
    shell: /usr/local/samba/bin/samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=BIND9_DLZ --realm={{ realm_nome }} --domain={{ domain }} --adminpass={{ password }}
    register: provision

  - debug:
      msg: "{{ provision.stdout }}"


## criar o arquivo de execucao do samba4 e inicializar automaticamente

  - name: Copiando o arquivo samba4 para pasta /etc/rc.d/init.d/
    copy: 
      src: samba4 
      dest: /etc/rc.d/init.d/
      owner: root
      group: root
      mode: 0755

## link simbolico 
  - name: link simbolico samba4
    shell: "{{ item.shell }}"
    loop:
      - { shell: "ln -s /etc/rc.d/init.d/samba4 /etc/rc3.d/s80samba4" }
      - { shell: "chkconfig --add samba4" }
      - { shell: "chkconfig samba4 on" }
...
