---
# tasks file for samba4



### Parando o firewall desabilidanando da inicializacao e desabilitando o SELINUX

  - name: Parando o firewall 
    systemd: name=firewalld state=stopped     
  
  - name: Desabilitar o servico Firewalld da inicializacao 
    systemd: name=firewalld enabled=no
  
  - name: Desabilitando o SELINUX (temp)
    selinux: state=disabled

  - name: Desabilitando o SELINUX (permanente)
    replace: 
      path=/etc/selinux/config
      regexp='SELINUX=enforcing'
      replace='SELINUX=disabled'


## Instalando os pacotes basicos para instalacao do samba4
  - name: Instalacao de repositorio epel
    yum: name=epel-release state=latest

  - name: Habilitando Powertol repositorio
    replace:
      path=/etc/yum.repos.d/CentOS-Stream-PowerTools.repo
      regexp='enabled=0'
      replace='enabled=1'

  - name: Atualizando lista de repositorios
    yum: name=* state=latest

  - name: Instalacao de pacotes basicos
    yum: name={{ common_packges }} state=latest


## editar o arquivo /etc/hosts e nome da maquina

  - name: editar arquivo /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "10.0.2.4 clti9dnfs1.clti9d.ad clti9dnfs1"
  
  - name: Mudando o nome do servidor
    ansible.builtin.hostname:
      name: clti9dnfs1



## editar o arquivo /etc/sysctl.conf

  - name: Editando arquivo /etc/sysctl.conf
    lineinfile:
      path: /etc/sysctl.conf
      line: "vm.swappiness = 0"

##Editando o /etc/resolv.conf


  - name: Editando o /etc/resolv.conf
    lineinfile:
      path: /etc/resolv.conf
      line: "{{ item.line }}"
    loop:
      - { line: "nameserver 10.0.2.4" }
      - { line: "nameserver 10.0.2.5" }
      - { line: "search clti9d.ad" }
      - { line: "domain clti9d.ad" }

## Movendo o instalador do samba para pasta /opt e descompactando o arquivo

  - name: Copiando o instalador do samba para pasta /opt
    copy: src=samba-latest.tar.gz dest=/opt

  - name: Extraindo o conteudo do instalador samba.tar.gz
    unarchive:  
      src: /opt/samba-latest.tar.gz
      dest: /opt/
      remote_src: yes


## executando o .configure && make && make install


  - name: executando o .configure && make && make install
    shell: ./configure.developer && make && make install
    args: 
      chdir: /opt/samba-4.15.2/

...
